In [10]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

toxin = pd.read_csv("toxin.csv")
toxin.head()

,TRI_FACILITY_ID,DOC_CTRL_NUM,FACILITY_NAME,STREET_ADDRESS,CITY_NAME,COUNTY_NAME,STATE_COUNTY_FIPS_CODE,STATE_ABBR,ZIP_CODE,REGION,...,RELEASE_RANGE_CODE,TOTAL_RELEASE,REL_EST_AMT,RELEASE_NA,RELEASE_BASIS_EST_CODE,WATER_SEQUENCE_NUM,STREAM_NAME,STORM_WATER_NA,STORM_WATER_PERCENT,REACH_CODE
0,15226MTTHW1315W,1396105260741,MATTHEWS INTERNATIONAL CORP,1315 W LIBERTY AVE,PITTSBURGH,ALLEGHENY,42003,PA,15226,3,...,NaN,NaN,0.0,0,NaN,1,NaN,0,NaN,NaN
1,15025RSTCH400ST,1388025294164,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,42003,PA,15025,3,...,NaN,0.0,0.0,0,O,1,PETERS CREEK,0,NaN,NaN
2,15144PPGND125CO,1310208167751,PPG INDUSTRIESINC-SPRINGDALE COMPLEX,125 COLFAX ST,SPRINGDALE,ALLEGHENY,42003,PA,15144,3,...,NaN,NaN,0.0,1,NaN,1,NaN,0,NaN,NaN
3,15139TRNGL931TH,1389035450600,GLOBAL CIRCUITS INC.,931 3RD ST,OAKMONT,ALLEGHENY,42003,PA,15139,3,...,NaN,NaN,0.0,1,NaN,1,NaN,1,NaN,NaN
4,15020SNCCHBUNOL,1302200503023,UNIVAR SOLUTIONS USA INC - BUNOLA BRANCH,328 BUNOLA RIVER RD,BUNOLA,ALLEGHENY,42003,PA,15020,3,...,NaN,NaN,0.0,0,NaN,1,NaN,0,NaN,NaN

In [11]:
cities = toxin['CITY_NAME'] == "PITTSBURGH"
pittsburgh = toxin[cities]
pittsburgh.head()

,TRI_FACILITY_ID,DOC_CTRL_NUM,FACILITY_NAME,STREET_ADDRESS,CITY_NAME,COUNTY_NAME,STATE_COUNTY_FIPS_CODE,STATE_ABBR,ZIP_CODE,REGION,...,RELEASE_RANGE_CODE,TOTAL_RELEASE,REL_EST_AMT,RELEASE_NA,RELEASE_BASIS_EST_CODE,WATER_SEQUENCE_NUM,STREAM_NAME,STORM_WATER_NA,STORM_WATER_PERCENT,REACH_CODE
0,15226MTTHW1315W,1396105260741,MATTHEWS INTERNATIONAL CORP,1315 W LIBERTY AVE,PITTSBURGH,ALLEGHENY,42003,PA,15226,3,...,NaN,NaN,0.0,0,NaN,1,NaN,0,NaN,NaN
8,15233THVLS2000W,1393070296494,SHERWIN-WILLIAMS CO,2000 WESTHALL ST,PITTSBURGH,ALLEGHENY,42003,PA,15233,3,...,NaN,NaN,0.0,1,NaN,1,NaN,1,NaN,NaN
20,15201XXNCM34THS,1393075550259,EXXON CO USA PITTSBURGH PLANT,100 35TH ST,PITTSBURGH,ALLEGHENY,42003,PA,15201,3,...,NaN,0.0,0.0,0,M,1,ALLEGHENY RIVER,0,100.0,NaN
21,15225CLGNC200NE,1300140375647,CALGON CARBON CORP NEVILLE ISLAND PLANT,200 NEVILLE RD,PITTSBURGH,ALLEGHENY,42003,PA,15225,3,...,NaN,NaN,0.0,0,NaN,1,NaN,0,NaN,NaN
23,15225WTSNSCORNE,1316215159841,WATSON STANDARD CO (NEVILLE ISLAND PLANT),2895 GRAND AVE,PITTSBURGH,ALLEGHENY,42003,PA,15225,3,...,NaN,NaN,0.0,1,NaN,1,NaN,0,NaN,NaN