In [2]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

toxin = pd.read_csv("toxin.csv")
toxin.head()

,TRI_FACILITY_ID,DOC_CTRL_NUM,FACILITY_NAME,STREET_ADDRESS,CITY_NAME,COUNTY_NAME,STATE_COUNTY_FIPS_CODE,STATE_ABBR,ZIP_CODE,REGION,...,RELEASE_RANGE_CODE,TOTAL_RELEASE,REL_EST_AMT,RELEASE_NA,RELEASE_BASIS_EST_CODE,WATER_SEQUENCE_NUM,STREAM_NAME,STORM_WATER_NA,STORM_WATER_PERCENT,REACH_CODE
0,15226MTTHW1315W,1396105260741,MATTHEWS INTERNATIONAL CORP,1315 W LIBERTY AVE,PITTSBURGH,ALLEGHENY,42003,PA,15226,3,...,NaN,NaN,0.0,0,NaN,1,NaN,0,NaN,NaN
1,15025RSTCH400ST,1388025294164,KOPPERS INC CLAIRTON TAR PLANT,300 N STATE ST,CLAIRTON,ALLEGHENY,42003,PA,15025,3,...,NaN,0.0,0.0,0,O,1,PETERS CREEK,0,NaN,NaN
2,15144PPGND125CO,1310208167751,PPG INDUSTRIESINC-SPRINGDALE COMPLEX,125 COLFAX ST,SPRINGDALE,ALLEGHENY,42003,PA,15144,3,...,NaN,NaN,0.0,1,NaN,1,NaN,0,NaN,NaN
3,15139TRNGL931TH,1389035450600,GLOBAL CIRCUITS INC.,931 3RD ST,OAKMONT,ALLEGHENY,42003,PA,15139,3,...,NaN,NaN,0.0,1,NaN,1,NaN,1,NaN,NaN
4,15020SNCCHBUNOL,1302200503023,UNIVAR SOLUTIONS USA INC - BUNOLA BRANCH,328 BUNOLA RIVER RD,BUNOLA,ALLEGHENY,42003,PA,15020,3,...,NaN,NaN,0.0,0,NaN,1,NaN,0,NaN,NaN

In [ ]:
pittsburgh = toxin["CITY_NAME"].unique()
print (towns)